# Generated by Django 5.1.2 on 2024-10-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_language_source_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_sources', to='feeds.category'),
        ),
        migrations.AlterField(
            model_name='source',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_sources', to='feeds.language'),
        ),
    ]
