# Generated by Django 5.1.2 on 2024-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_source_category_alter_source_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='languages',
            field=models.ManyToManyField(related_name='categories', to='feeds.language'),
        ),
    ]
