# Generated by Django 5.1.2 on 2024-10-22 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_article_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to='articles.article'),
        ),
    ]
