# Generated by Django 5.1.2 on 2024-10-26 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_userarticle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fetched_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
