# Generated by Django 5.1.2 on 2024-11-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_fetched_date_userarticle_fetched_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedarticle',
            name='notes',
        ),
    ]
