# Generated by Django 5.1.2 on 2024-11-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_savedarticle_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedArticle',
        ),
    ]
